version: "3.8"

networks:
  docknode-bnb:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:

services:
  fullnode:
    image: "ghcr.io/bnb-chain/bsc:latest"
    user: 1000:1000
    restart: unless-stopped
    expose:
      - 8545
      - 6060
    ports:
      - "30303:30303"
      - "30311:30311"
    volumes:
      - ./bnb/config:/bsc/config:ro
      - ./bnb/db:/bsc/.ethereum:rw
    command: >
      --bsc
      --http --http.vhosts=* --http.addr 0.0.0.0 --http.port 8545
      --syncmode snap
    networks:
      - docknode-bnb

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - docknode-bnb

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 9101:9101
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - METRICS_USERS=${METRICS_USERS:?err}
      - RPC_USERS=${RPC_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-bnb
